version: 1

source:
  root: ~/pipe-works-development/pipeworks_mud_server/data/worlds/pipeworks_web/policies

targets:
  - name: image-generator
    root: ~/pipe-works-development/pipeworks-image-generator/data/worlds/pipeworks_web/policies

  - name: axis-descriptor-lab
    root: ~/pipe-works-development/pipeworks_axis_descriptor_lab/app/worlds/pipeworks_web/policies
